# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import app_pb2 as app__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppManagerStub(object):
    """AppManager service for managing application containers
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InstallApp = channel.unary_unary(
                '/appmanager.AppManager/InstallApp',
                request_serializer=app__pb2.InstallRequest.SerializeToString,
                response_deserializer=app__pb2.InstallResponse.FromString,
                _registered_method=True)
        self.AsyncInstallApp = channel.unary_unary(
                '/appmanager.AppManager/AsyncInstallApp',
                request_serializer=app__pb2.AsyncInstallRequest.SerializeToString,
                response_deserializer=app__pb2.AsyncInstallResponse.FromString,
                _registered_method=True)
        self.GetInstallProgress = channel.unary_unary(
                '/appmanager.AppManager/GetInstallProgress',
                request_serializer=app__pb2.InstallProgressRequest.SerializeToString,
                response_deserializer=app__pb2.InstallProgressResponse.FromString,
                _registered_method=True)
        self.StartApp = channel.unary_unary(
                '/appmanager.AppManager/StartApp',
                request_serializer=app__pb2.StartRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.StopApp = channel.unary_unary(
                '/appmanager.AppManager/StopApp',
                request_serializer=app__pb2.StopRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.UninstallApp = channel.unary_unary(
                '/appmanager.AppManager/UninstallApp',
                request_serializer=app__pb2.UninstallRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.ListApps = channel.unary_unary(
                '/appmanager.AppManager/ListApps',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app__pb2.AppList.FromString,
                _registered_method=True)
        self.GetApp = channel.unary_unary(
                '/appmanager.AppManager/GetApp',
                request_serializer=app__pb2.GetAppRequest.SerializeToString,
                response_deserializer=app__pb2.AppInfo.FromString,
                _registered_method=True)
        self.GetAppStats = channel.unary_unary(
                '/appmanager.AppManager/GetAppStats',
                request_serializer=app__pb2.GetAppRequest.SerializeToString,
                response_deserializer=app__pb2.AppStats.FromString,
                _registered_method=True)
        self.GetAppLogs = channel.unary_stream(
                '/appmanager.AppManager/GetAppLogs',
                request_serializer=app__pb2.GetLogsRequest.SerializeToString,
                response_deserializer=app__pb2.LogLine.FromString,
                _registered_method=True)
        self.GetDiskUsage = channel.unary_unary(
                '/appmanager.AppManager/GetDiskUsage',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app__pb2.DiskUsageResponse.FromString,
                _registered_method=True)
        self.PruneResources = channel.unary_unary(
                '/appmanager.AppManager/PruneResources',
                request_serializer=app__pb2.PruneRequest.SerializeToString,
                response_deserializer=app__pb2.PruneResponse.FromString,
                _registered_method=True)
        self.ExecContainer = channel.stream_stream(
                '/appmanager.AppManager/ExecContainer',
                request_serializer=app__pb2.ExecInput.SerializeToString,
                response_deserializer=app__pb2.ExecOutput.FromString,
                _registered_method=True)
        self.SendSignal = channel.unary_unary(
                '/appmanager.AppManager/SendSignal',
                request_serializer=app__pb2.SendSignalRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.ListImages = channel.unary_unary(
                '/appmanager.AppManager/ListImages',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=app__pb2.ImageList.FromString,
                _registered_method=True)
        self.RemoveImage = channel.unary_unary(
                '/appmanager.AppManager/RemoveImage',
                request_serializer=app__pb2.RemoveImageRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.InspectApp = channel.unary_unary(
                '/appmanager.AppManager/InspectApp',
                request_serializer=app__pb2.GetAppRequest.SerializeToString,
                response_deserializer=app__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.BatchOperation = channel.unary_unary(
                '/appmanager.AppManager/BatchOperation',
                request_serializer=app__pb2.BatchRequest.SerializeToString,
                response_deserializer=app__pb2.BatchResponse.FromString,
                _registered_method=True)
        self.RegisterWebUrl = channel.unary_unary(
                '/appmanager.AppManager/RegisterWebUrl',
                request_serializer=app__pb2.RegisterWebUrlRequest.SerializeToString,
                response_deserializer=app__pb2.RegisterWebUrlResponse.FromString,
                _registered_method=True)
        self.ListContainers = channel.unary_unary(
                '/appmanager.AppManager/ListContainers',
                request_serializer=app__pb2.ListContainersRequest.SerializeToString,
                response_deserializer=app__pb2.ContainerList.FromString,
                _registered_method=True)
        self.GetContainer = channel.unary_unary(
                '/appmanager.AppManager/GetContainer',
                request_serializer=app__pb2.GetContainerRequest.SerializeToString,
                response_deserializer=app__pb2.ContainerDetail.FromString,
                _registered_method=True)
        self.GetContainerStats = channel.unary_unary(
                '/appmanager.AppManager/GetContainerStats',
                request_serializer=app__pb2.GetContainerRequest.SerializeToString,
                response_deserializer=app__pb2.ContainerStats.FromString,
                _registered_method=True)
        self.GetContainerLogs = channel.unary_stream(
                '/appmanager.AppManager/GetContainerLogs',
                request_serializer=app__pb2.GetContainerLogsRequest.SerializeToString,
                response_deserializer=app__pb2.LogLine.FromString,
                _registered_method=True)
        self.StartContainer = channel.unary_unary(
                '/appmanager.AppManager/StartContainer',
                request_serializer=app__pb2.ContainerRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.StopContainer = channel.unary_unary(
                '/appmanager.AppManager/StopContainer',
                request_serializer=app__pb2.ContainerRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.RestartContainer = channel.unary_unary(
                '/appmanager.AppManager/RestartContainer',
                request_serializer=app__pb2.ContainerRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)
        self.RemoveContainer = channel.unary_unary(
                '/appmanager.AppManager/RemoveContainer',
                request_serializer=app__pb2.RemoveContainerRequest.SerializeToString,
                response_deserializer=app__pb2.Status.FromString,
                _registered_method=True)


class AppManagerServicer(object):
    """AppManager service for managing application containers
    """

    def InstallApp(self, request, context):
        """Install an application from manifest and image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsyncInstallApp(self, request, context):
        """Async install — returns task_id immediately, poll GetInstallProgress for status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstallProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartApp(self, request, context):
        """Start a stopped application
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopApp(self, request, context):
        """Stop a running application
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UninstallApp(self, request, context):
        """Uninstall an application
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApps(self, request, context):
        """List all installed applications
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApp(self, request, context):
        """Get application information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppStats(self, request, context):
        """Get application statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppLogs(self, request, context):
        """Get application logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiskUsage(self, request, context):
        """High priority RPCs
        Get disk usage statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PruneResources(self, request, context):
        """Prune unused resources (containers, images, snapshots)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecContainer(self, request_iterator, context):
        """Execute command in container (interactive shell)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSignal(self, request, context):
        """Send a signal to a running container (for dev mode reload)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListImages(self, request, context):
        """Medium priority RPCs
        List all images
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveImage(self, request, context):
        """Remove an image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectApp(self, request, context):
        """Inspect container details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchOperation(self, request, context):
        """Batch operations on multiple apps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWebUrl(self, request, context):
        """Register web URL for an app (called by app via SDK)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContainers(self, request, context):
        """Raw container operations (Direct containerd access)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContainerLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallApp,
                    request_deserializer=app__pb2.InstallRequest.FromString,
                    response_serializer=app__pb2.InstallResponse.SerializeToString,
            ),
            'AsyncInstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.AsyncInstallApp,
                    request_deserializer=app__pb2.AsyncInstallRequest.FromString,
                    response_serializer=app__pb2.AsyncInstallResponse.SerializeToString,
            ),
            'GetInstallProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstallProgress,
                    request_deserializer=app__pb2.InstallProgressRequest.FromString,
                    response_serializer=app__pb2.InstallProgressResponse.SerializeToString,
            ),
            'StartApp': grpc.unary_unary_rpc_method_handler(
                    servicer.StartApp,
                    request_deserializer=app__pb2.StartRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'StopApp': grpc.unary_unary_rpc_method_handler(
                    servicer.StopApp,
                    request_deserializer=app__pb2.StopRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'UninstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.UninstallApp,
                    request_deserializer=app__pb2.UninstallRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'ListApps': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApps,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app__pb2.AppList.SerializeToString,
            ),
            'GetApp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApp,
                    request_deserializer=app__pb2.GetAppRequest.FromString,
                    response_serializer=app__pb2.AppInfo.SerializeToString,
            ),
            'GetAppStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppStats,
                    request_deserializer=app__pb2.GetAppRequest.FromString,
                    response_serializer=app__pb2.AppStats.SerializeToString,
            ),
            'GetAppLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAppLogs,
                    request_deserializer=app__pb2.GetLogsRequest.FromString,
                    response_serializer=app__pb2.LogLine.SerializeToString,
            ),
            'GetDiskUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiskUsage,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app__pb2.DiskUsageResponse.SerializeToString,
            ),
            'PruneResources': grpc.unary_unary_rpc_method_handler(
                    servicer.PruneResources,
                    request_deserializer=app__pb2.PruneRequest.FromString,
                    response_serializer=app__pb2.PruneResponse.SerializeToString,
            ),
            'ExecContainer': grpc.stream_stream_rpc_method_handler(
                    servicer.ExecContainer,
                    request_deserializer=app__pb2.ExecInput.FromString,
                    response_serializer=app__pb2.ExecOutput.SerializeToString,
            ),
            'SendSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSignal,
                    request_deserializer=app__pb2.SendSignalRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'ListImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListImages,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=app__pb2.ImageList.SerializeToString,
            ),
            'RemoveImage': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveImage,
                    request_deserializer=app__pb2.RemoveImageRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'InspectApp': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectApp,
                    request_deserializer=app__pb2.GetAppRequest.FromString,
                    response_serializer=app__pb2.InspectResponse.SerializeToString,
            ),
            'BatchOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchOperation,
                    request_deserializer=app__pb2.BatchRequest.FromString,
                    response_serializer=app__pb2.BatchResponse.SerializeToString,
            ),
            'RegisterWebUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWebUrl,
                    request_deserializer=app__pb2.RegisterWebUrlRequest.FromString,
                    response_serializer=app__pb2.RegisterWebUrlResponse.SerializeToString,
            ),
            'ListContainers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContainers,
                    request_deserializer=app__pb2.ListContainersRequest.FromString,
                    response_serializer=app__pb2.ContainerList.SerializeToString,
            ),
            'GetContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainer,
                    request_deserializer=app__pb2.GetContainerRequest.FromString,
                    response_serializer=app__pb2.ContainerDetail.SerializeToString,
            ),
            'GetContainerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContainerStats,
                    request_deserializer=app__pb2.GetContainerRequest.FromString,
                    response_serializer=app__pb2.ContainerStats.SerializeToString,
            ),
            'GetContainerLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetContainerLogs,
                    request_deserializer=app__pb2.GetContainerLogsRequest.FromString,
                    response_serializer=app__pb2.LogLine.SerializeToString,
            ),
            'StartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartContainer,
                    request_deserializer=app__pb2.ContainerRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'StopContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StopContainer,
                    request_deserializer=app__pb2.ContainerRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'RestartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartContainer,
                    request_deserializer=app__pb2.ContainerRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
            'RemoveContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContainer,
                    request_deserializer=app__pb2.RemoveContainerRequest.FromString,
                    response_serializer=app__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'appmanager.AppManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('appmanager.AppManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppManager(object):
    """AppManager service for managing application containers
    """

    @staticmethod
    def InstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/InstallApp',
            app__pb2.InstallRequest.SerializeToString,
            app__pb2.InstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsyncInstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/AsyncInstallApp',
            app__pb2.AsyncInstallRequest.SerializeToString,
            app__pb2.AsyncInstallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstallProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetInstallProgress',
            app__pb2.InstallProgressRequest.SerializeToString,
            app__pb2.InstallProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/StartApp',
            app__pb2.StartRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/StopApp',
            app__pb2.StopRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UninstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/UninstallApp',
            app__pb2.UninstallRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/ListApps',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app__pb2.AppList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetApp',
            app__pb2.GetAppRequest.SerializeToString,
            app__pb2.AppInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetAppStats',
            app__pb2.GetAppRequest.SerializeToString,
            app__pb2.AppStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/appmanager.AppManager/GetAppLogs',
            app__pb2.GetLogsRequest.SerializeToString,
            app__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiskUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetDiskUsage',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app__pb2.DiskUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PruneResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/PruneResources',
            app__pb2.PruneRequest.SerializeToString,
            app__pb2.PruneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecContainer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/appmanager.AppManager/ExecContainer',
            app__pb2.ExecInput.SerializeToString,
            app__pb2.ExecOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/SendSignal',
            app__pb2.SendSignalRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/ListImages',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            app__pb2.ImageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/RemoveImage',
            app__pb2.RemoveImageRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/InspectApp',
            app__pb2.GetAppRequest.SerializeToString,
            app__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/BatchOperation',
            app__pb2.BatchRequest.SerializeToString,
            app__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWebUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/RegisterWebUrl',
            app__pb2.RegisterWebUrlRequest.SerializeToString,
            app__pb2.RegisterWebUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContainers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/ListContainers',
            app__pb2.ListContainersRequest.SerializeToString,
            app__pb2.ContainerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetContainer',
            app__pb2.GetContainerRequest.SerializeToString,
            app__pb2.ContainerDetail.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/GetContainerStats',
            app__pb2.GetContainerRequest.SerializeToString,
            app__pb2.ContainerStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContainerLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/appmanager.AppManager/GetContainerLogs',
            app__pb2.GetContainerLogsRequest.SerializeToString,
            app__pb2.LogLine.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/StartContainer',
            app__pb2.ContainerRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/StopContainer',
            app__pb2.ContainerRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/RestartContainer',
            app__pb2.ContainerRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/appmanager.AppManager/RemoveContainer',
            app__pb2.RemoveContainerRequest.SerializeToString,
            app__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
