# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import camera_pb2 as camera__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraControlStub(object):
    """Camera Control Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartOneShotAutofocus = channel.unary_unary(
                '/aipc.camera.CameraControl/StartOneShotAutofocus',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.AutofocusJobResponse.FromString,
                _registered_method=True)
        self.StartZoomFollow = channel.unary_unary(
                '/aipc.camera.CameraControl/StartZoomFollow',
                request_serializer=camera__pb2.AutofocusZoomFollowRequest.SerializeToString,
                response_deserializer=camera__pb2.AutofocusJobResponse.FromString,
                _registered_method=True)
        self.GetAutofocusStatus = channel.unary_unary(
                '/aipc.camera.CameraControl/GetAutofocusStatus',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.AutofocusStatusResponse.FromString,
                _registered_method=True)
        self.CancelAutofocus = channel.unary_unary(
                '/aipc.camera.CameraControl/CancelAutofocus',
                request_serializer=camera__pb2.AutofocusJobRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.InvalidateAutofocusAnchor = channel.unary_unary(
                '/aipc.camera.CameraControl/InvalidateAutofocusAnchor',
                request_serializer=camera__pb2.AutofocusInvalidateRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateISPSettings = channel.unary_unary(
                '/aipc.camera.CameraControl/UpdateISPSettings',
                request_serializer=camera__pb2.ISPUpdateRequest.SerializeToString,
                response_deserializer=camera__pb2.ISPUpdateResponse.FromString,
                _registered_method=True)
        self.GetISPConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/GetISPConfig',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.ISPConfigResponse.FromString,
                _registered_method=True)
        self.GetTransformConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/GetTransformConfig',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.TransformConfig.FromString,
                _registered_method=True)
        self.SetTransformConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/SetTransformConfig',
                request_serializer=camera__pb2.TransformConfig.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateEncoderConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/UpdateEncoderConfig',
                request_serializer=camera__pb2.EncoderConfigRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.SetRtspEnabled = channel.unary_unary(
                '/aipc.camera.CameraControl/SetRtspEnabled',
                request_serializer=camera__pb2.RtspEnabledRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateAiOverlay = channel.unary_unary(
                '/aipc.camera.CameraControl/UpdateAiOverlay',
                request_serializer=camera__pb2.AiOverlayConfig.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateOsdConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/UpdateOsdConfig',
                request_serializer=camera__pb2.OsdConfigRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.GetOsdConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/GetOsdConfig',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.OsdConfigResponse.FromString,
                _registered_method=True)
        self.ReconfigureEncoder = channel.unary_unary(
                '/aipc.camera.CameraControl/ReconfigureEncoder',
                request_serializer=camera__pb2.EncoderReconfigRequest.SerializeToString,
                response_deserializer=camera__pb2.EncoderReconfigResponse.FromString,
                _registered_method=True)
        self.GetProfile = channel.unary_unary(
                '/aipc.camera.CameraControl/GetProfile',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.GetProfileResponse.FromString,
                _registered_method=True)
        self.ListProfiles = channel.unary_unary(
                '/aipc.camera.CameraControl/ListProfiles',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.ListProfilesResponse.FromString,
                _registered_method=True)
        self.SwitchProfile = channel.unary_unary(
                '/aipc.camera.CameraControl/SwitchProfile',
                request_serializer=camera__pb2.SwitchProfileRequest.SerializeToString,
                response_deserializer=camera__pb2.EncoderReconfigResponse.FromString,
                _registered_method=True)
        self.BackupProfile = channel.unary_unary(
                '/aipc.camera.CameraControl/BackupProfile',
                request_serializer=camera__pb2.BackupProfileRequest.SerializeToString,
                response_deserializer=camera__pb2.BackupProfileResponse.FromString,
                _registered_method=True)
        self.ReconfigurePipeline = channel.unary_unary(
                '/aipc.camera.CameraControl/ReconfigurePipeline',
                request_serializer=camera__pb2.ReconfigurePipelineRequest.SerializeToString,
                response_deserializer=camera__pb2.ReconfigurePipelineResponse.FromString,
                _registered_method=True)
        self.GetSensorInfo = channel.unary_unary(
                '/aipc.camera.CameraControl/GetSensorInfo',
                request_serializer=camera__pb2.GetSensorInfoRequest.SerializeToString,
                response_deserializer=camera__pb2.SensorInfoResponse.FromString,
                _registered_method=True)
        self.GetStreamStatus = channel.unary_unary(
                '/aipc.camera.CameraControl/GetStreamStatus',
                request_serializer=camera__pb2.GetStreamStatusRequest.SerializeToString,
                response_deserializer=camera__pb2.GetStreamStatusResponse.FromString,
                _registered_method=True)
        self.AddStream = channel.unary_unary(
                '/aipc.camera.CameraControl/AddStream',
                request_serializer=camera__pb2.AddStreamRequest.SerializeToString,
                response_deserializer=camera__pb2.StreamOperationResponse.FromString,
                _registered_method=True)
        self.RemoveStream = channel.unary_unary(
                '/aipc.camera.CameraControl/RemoveStream',
                request_serializer=camera__pb2.RemoveStreamRequest.SerializeToString,
                response_deserializer=camera__pb2.StreamOperationResponse.FromString,
                _registered_method=True)
        self.SetIrCut = channel.unary_unary(
                '/aipc.camera.CameraControl/SetIrCut',
                request_serializer=camera__pb2.SetIrCutRequest.SerializeToString,
                response_deserializer=camera__pb2.SetIrCutResponse.FromString,
                _registered_method=True)
        self.GetIrCut = channel.unary_unary(
                '/aipc.camera.CameraControl/GetIrCut',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.SetIrCutResponse.FromString,
                _registered_method=True)
        self.SetLedDuty = channel.unary_unary(
                '/aipc.camera.CameraControl/SetLedDuty',
                request_serializer=camera__pb2.SetLedDutyRequest.SerializeToString,
                response_deserializer=camera__pb2.LedStatus.FromString,
                _registered_method=True)
        self.GetLedDuty = channel.unary_unary(
                '/aipc.camera.CameraControl/GetLedDuty',
                request_serializer=camera__pb2.GetLedDutyRequest.SerializeToString,
                response_deserializer=camera__pb2.LedStatus.FromString,
                _registered_method=True)
        self.GetDeviceHardwareStatus = channel.unary_unary(
                '/aipc.camera.CameraControl/GetDeviceHardwareStatus',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.DeviceHardwareStatus.FromString,
                _registered_method=True)
        self.McuRawRequest = channel.unary_unary(
                '/aipc.camera.CameraControl/McuRawRequest',
                request_serializer=camera__pb2.McuRawRequestMessage.SerializeToString,
                response_deserializer=camera__pb2.McuRawResponseMessage.FromString,
                _registered_method=True)
        self.SetFan = channel.unary_unary(
                '/aipc.camera.CameraControl/SetFan',
                request_serializer=camera__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetFan = channel.unary_unary(
                '/aipc.camera.CameraControl/GetFan',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetHeat = channel.unary_unary(
                '/aipc.camera.CameraControl/SetHeat',
                request_serializer=camera__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetHeat = channel.unary_unary(
                '/aipc.camera.CameraControl/GetHeat',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetRadar = channel.unary_unary(
                '/aipc.camera.CameraControl/SetRadar',
                request_serializer=camera__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetRadar = channel.unary_unary(
                '/aipc.camera.CameraControl/GetRadar',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetAlarmOut = channel.unary_unary(
                '/aipc.camera.CameraControl/SetAlarmOut',
                request_serializer=camera__pb2.AlarmOutRequest.SerializeToString,
                response_deserializer=camera__pb2.AlarmOutStatus.FromString,
                _registered_method=True)
        self.GetAlarmOut = channel.unary_unary(
                '/aipc.camera.CameraControl/GetAlarmOut',
                request_serializer=camera__pb2.AlarmOutRequest.SerializeToString,
                response_deserializer=camera__pb2.AlarmOutStatus.FromString,
                _registered_method=True)
        self.SetWiegandOut = channel.unary_unary(
                '/aipc.camera.CameraControl/SetWiegandOut',
                request_serializer=camera__pb2.WiegandOutRequest.SerializeToString,
                response_deserializer=camera__pb2.AlarmOutStatus.FromString,
                _registered_method=True)
        self.GetWiegandOut = channel.unary_unary(
                '/aipc.camera.CameraControl/GetWiegandOut',
                request_serializer=camera__pb2.WiegandOutRequest.SerializeToString,
                response_deserializer=camera__pb2.AlarmOutStatus.FromString,
                _registered_method=True)
        self.GetAlarmOutputs = channel.unary_unary(
                '/aipc.camera.CameraControl/GetAlarmOutputs',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.AlarmOutputsState.FromString,
                _registered_method=True)
        self.Rs485Init = channel.unary_unary(
                '/aipc.camera.CameraControl/Rs485Init',
                request_serializer=camera__pb2.Rs485InitRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.Rs485Deinit = channel.unary_unary(
                '/aipc.camera.CameraControl/Rs485Deinit',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.Rs485Tx = channel.unary_unary(
                '/aipc.camera.CameraControl/Rs485Tx',
                request_serializer=camera__pb2.Rs485TxRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/aipc.camera.CameraControl/GetCapabilities',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.ListAudioCaptureDevices = channel.unary_unary(
                '/aipc.camera.CameraControl/ListAudioCaptureDevices',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.ListAudioDevicesResponse.FromString,
                _registered_method=True)
        self.ListAudioPlaybackDevices = channel.unary_unary(
                '/aipc.camera.CameraControl/ListAudioPlaybackDevices',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.ListAudioDevicesResponse.FromString,
                _registered_method=True)
        self.StartAudioCapture = channel.unary_unary(
                '/aipc.camera.CameraControl/StartAudioCapture',
                request_serializer=camera__pb2.AudioConfigRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.StopAudioCapture = channel.unary_unary(
                '/aipc.camera.CameraControl/StopAudioCapture',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.GetAudioStatus = channel.unary_unary(
                '/aipc.camera.CameraControl/GetAudioStatus',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.AudioStatusResponse.FromString,
                _registered_method=True)
        self.SetAudioConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/SetAudioConfig',
                request_serializer=camera__pb2.AudioConfigRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.StartAudioPlayback = channel.unary_unary(
                '/aipc.camera.CameraControl/StartAudioPlayback',
                request_serializer=camera__pb2.AudioConfigRequest.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.StreamAudioPcm = channel.stream_unary(
                '/aipc.camera.CameraControl/StreamAudioPcm',
                request_serializer=camera__pb2.AudioPcmChunk.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.StopAudioPlayback = channel.unary_unary(
                '/aipc.camera.CameraControl/StopAudioPlayback',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)
        self.GetPrivacyMaskConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/GetPrivacyMaskConfig',
                request_serializer=camera__pb2.Empty.SerializeToString,
                response_deserializer=camera__pb2.PrivacyMaskConfig.FromString,
                _registered_method=True)
        self.SetPrivacyMaskConfig = channel.unary_unary(
                '/aipc.camera.CameraControl/SetPrivacyMaskConfig',
                request_serializer=camera__pb2.PrivacyMaskConfig.SerializeToString,
                response_deserializer=camera__pb2.Status.FromString,
                _registered_method=True)


class CameraControlServicer(object):
    """Camera Control Service
    """

    def StartOneShotAutofocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartZoomFollow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAutofocusStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAutofocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateAutofocusAnchor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateISPSettings(self, request, context):
        """Update ISP image pipeline settings (brightness, contrast, saturation, sharpness)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetISPConfig(self, request, context):
        """Get current ISP configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransformConfig(self, request, context):
        """Get current transform configuration (rotation, flip, dewarp, grayscale)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTransformConfig(self, request, context):
        """Update transform configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEncoderConfig(self, request, context):
        """Dynamic encoder configuration (no restart required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRtspEnabled(self, request, context):
        """Enable/disable RTSP server (no restart required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAiOverlay(self, request, context):
        """Update AI overlay configuration (no restart required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOsdConfig(self, request, context):
        """Update OSD configuration (no restart required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOsdConfig(self, request, context):
        """Get current OSD configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconfigureEncoder(self, request, context):
        """Full encoder reconfiguration (brief restart required, ~100ms)
        Use this for resolution/codec changes that require encoder restart
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfile(self, request, context):
        """Profile management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconfigurePipeline(self, request, context):
        """Full pipeline reconfiguration (stream count change, ~2s interruption)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensorInfo(self, request, context):
        """Get sensor module information (model, I2C, pixel format)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamStatus(self, request, context):
        """Get real-time stream status (encoder health, active/idle/error)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddStream(self, request, context):
        """Dynamic stream add/remove (incremental, ~100-500ms)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIrCut(self, request, context):
        """IR-Cut filter control (day/night mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIrCut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLedDuty(self, request, context):
        """LED / White Light / IR LED control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLedDuty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceHardwareStatus(self, request, context):
        """Device status (sensors, MCU version, LED state)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def McuRawRequest(self, request, context):
        """MCU raw request (PTZ, GPIO, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFan(self, request, context):
        """Environment control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRadar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRadar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAlarmOut(self, request, context):
        """Alarm I/O
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlarmOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWiegandOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWiegandOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlarmOutputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Init(self, request, context):
        """RS485
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Deinit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Tx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Capabilities (auto-detected from HAL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAudioCaptureDevices(self, request, context):
        """Audio capture
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAudioPlaybackDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAudioCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudioCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudioStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAudioConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAudioPlayback(self, request, context):
        """Audio playback (two-way talk)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAudioPcm(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAudioPlayback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrivacyMaskConfig(self, request, context):
        """Privacy mask
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPrivacyMaskConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartOneShotAutofocus': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOneShotAutofocus,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.AutofocusJobResponse.SerializeToString,
            ),
            'StartZoomFollow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartZoomFollow,
                    request_deserializer=camera__pb2.AutofocusZoomFollowRequest.FromString,
                    response_serializer=camera__pb2.AutofocusJobResponse.SerializeToString,
            ),
            'GetAutofocusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutofocusStatus,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.AutofocusStatusResponse.SerializeToString,
            ),
            'CancelAutofocus': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAutofocus,
                    request_deserializer=camera__pb2.AutofocusJobRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'InvalidateAutofocusAnchor': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateAutofocusAnchor,
                    request_deserializer=camera__pb2.AutofocusInvalidateRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'UpdateISPSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateISPSettings,
                    request_deserializer=camera__pb2.ISPUpdateRequest.FromString,
                    response_serializer=camera__pb2.ISPUpdateResponse.SerializeToString,
            ),
            'GetISPConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetISPConfig,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.ISPConfigResponse.SerializeToString,
            ),
            'GetTransformConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransformConfig,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.TransformConfig.SerializeToString,
            ),
            'SetTransformConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTransformConfig,
                    request_deserializer=camera__pb2.TransformConfig.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'UpdateEncoderConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEncoderConfig,
                    request_deserializer=camera__pb2.EncoderConfigRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'SetRtspEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRtspEnabled,
                    request_deserializer=camera__pb2.RtspEnabledRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'UpdateAiOverlay': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAiOverlay,
                    request_deserializer=camera__pb2.AiOverlayConfig.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'UpdateOsdConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOsdConfig,
                    request_deserializer=camera__pb2.OsdConfigRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'GetOsdConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOsdConfig,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.OsdConfigResponse.SerializeToString,
            ),
            'ReconfigureEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconfigureEncoder,
                    request_deserializer=camera__pb2.EncoderReconfigRequest.FromString,
                    response_serializer=camera__pb2.EncoderReconfigResponse.SerializeToString,
            ),
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.GetProfileResponse.SerializeToString,
            ),
            'ListProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfiles,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.ListProfilesResponse.SerializeToString,
            ),
            'SwitchProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchProfile,
                    request_deserializer=camera__pb2.SwitchProfileRequest.FromString,
                    response_serializer=camera__pb2.EncoderReconfigResponse.SerializeToString,
            ),
            'BackupProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.BackupProfile,
                    request_deserializer=camera__pb2.BackupProfileRequest.FromString,
                    response_serializer=camera__pb2.BackupProfileResponse.SerializeToString,
            ),
            'ReconfigurePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.ReconfigurePipeline,
                    request_deserializer=camera__pb2.ReconfigurePipelineRequest.FromString,
                    response_serializer=camera__pb2.ReconfigurePipelineResponse.SerializeToString,
            ),
            'GetSensorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensorInfo,
                    request_deserializer=camera__pb2.GetSensorInfoRequest.FromString,
                    response_serializer=camera__pb2.SensorInfoResponse.SerializeToString,
            ),
            'GetStreamStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamStatus,
                    request_deserializer=camera__pb2.GetStreamStatusRequest.FromString,
                    response_serializer=camera__pb2.GetStreamStatusResponse.SerializeToString,
            ),
            'AddStream': grpc.unary_unary_rpc_method_handler(
                    servicer.AddStream,
                    request_deserializer=camera__pb2.AddStreamRequest.FromString,
                    response_serializer=camera__pb2.StreamOperationResponse.SerializeToString,
            ),
            'RemoveStream': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveStream,
                    request_deserializer=camera__pb2.RemoveStreamRequest.FromString,
                    response_serializer=camera__pb2.StreamOperationResponse.SerializeToString,
            ),
            'SetIrCut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIrCut,
                    request_deserializer=camera__pb2.SetIrCutRequest.FromString,
                    response_serializer=camera__pb2.SetIrCutResponse.SerializeToString,
            ),
            'GetIrCut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIrCut,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.SetIrCutResponse.SerializeToString,
            ),
            'SetLedDuty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLedDuty,
                    request_deserializer=camera__pb2.SetLedDutyRequest.FromString,
                    response_serializer=camera__pb2.LedStatus.SerializeToString,
            ),
            'GetLedDuty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLedDuty,
                    request_deserializer=camera__pb2.GetLedDutyRequest.FromString,
                    response_serializer=camera__pb2.LedStatus.SerializeToString,
            ),
            'GetDeviceHardwareStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceHardwareStatus,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.DeviceHardwareStatus.SerializeToString,
            ),
            'McuRawRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.McuRawRequest,
                    request_deserializer=camera__pb2.McuRawRequestMessage.FromString,
                    response_serializer=camera__pb2.McuRawResponseMessage.SerializeToString,
            ),
            'SetFan': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFan,
                    request_deserializer=camera__pb2.EnvCtrlRequest.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetFan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFan,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetHeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeat,
                    request_deserializer=camera__pb2.EnvCtrlRequest.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetHeat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeat,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetRadar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRadar,
                    request_deserializer=camera__pb2.EnvCtrlRequest.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetRadar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRadar,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetAlarmOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAlarmOut,
                    request_deserializer=camera__pb2.AlarmOutRequest.FromString,
                    response_serializer=camera__pb2.AlarmOutStatus.SerializeToString,
            ),
            'GetAlarmOut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarmOut,
                    request_deserializer=camera__pb2.AlarmOutRequest.FromString,
                    response_serializer=camera__pb2.AlarmOutStatus.SerializeToString,
            ),
            'SetWiegandOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWiegandOut,
                    request_deserializer=camera__pb2.WiegandOutRequest.FromString,
                    response_serializer=camera__pb2.AlarmOutStatus.SerializeToString,
            ),
            'GetWiegandOut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWiegandOut,
                    request_deserializer=camera__pb2.WiegandOutRequest.FromString,
                    response_serializer=camera__pb2.AlarmOutStatus.SerializeToString,
            ),
            'GetAlarmOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarmOutputs,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.AlarmOutputsState.SerializeToString,
            ),
            'Rs485Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Init,
                    request_deserializer=camera__pb2.Rs485InitRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'Rs485Deinit': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Deinit,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'Rs485Tx': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Tx,
                    request_deserializer=camera__pb2.Rs485TxRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'ListAudioCaptureDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAudioCaptureDevices,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.ListAudioDevicesResponse.SerializeToString,
            ),
            'ListAudioPlaybackDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAudioPlaybackDevices,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.ListAudioDevicesResponse.SerializeToString,
            ),
            'StartAudioCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAudioCapture,
                    request_deserializer=camera__pb2.AudioConfigRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'StopAudioCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudioCapture,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'GetAudioStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudioStatus,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.AudioStatusResponse.SerializeToString,
            ),
            'SetAudioConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAudioConfig,
                    request_deserializer=camera__pb2.AudioConfigRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'StartAudioPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAudioPlayback,
                    request_deserializer=camera__pb2.AudioConfigRequest.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'StreamAudioPcm': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAudioPcm,
                    request_deserializer=camera__pb2.AudioPcmChunk.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'StopAudioPlayback': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAudioPlayback,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
            'GetPrivacyMaskConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrivacyMaskConfig,
                    request_deserializer=camera__pb2.Empty.FromString,
                    response_serializer=camera__pb2.PrivacyMaskConfig.SerializeToString,
            ),
            'SetPrivacyMaskConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPrivacyMaskConfig,
                    request_deserializer=camera__pb2.PrivacyMaskConfig.FromString,
                    response_serializer=camera__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipc.camera.CameraControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipc.camera.CameraControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraControl(object):
    """Camera Control Service
    """

    @staticmethod
    def StartOneShotAutofocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StartOneShotAutofocus',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.AutofocusJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartZoomFollow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StartZoomFollow',
            camera__pb2.AutofocusZoomFollowRequest.SerializeToString,
            camera__pb2.AutofocusJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAutofocusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetAutofocusStatus',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.AutofocusStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAutofocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/CancelAutofocus',
            camera__pb2.AutofocusJobRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateAutofocusAnchor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/InvalidateAutofocusAnchor',
            camera__pb2.AutofocusInvalidateRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateISPSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/UpdateISPSettings',
            camera__pb2.ISPUpdateRequest.SerializeToString,
            camera__pb2.ISPUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetISPConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetISPConfig',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.ISPConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransformConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetTransformConfig',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.TransformConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTransformConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetTransformConfig',
            camera__pb2.TransformConfig.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEncoderConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/UpdateEncoderConfig',
            camera__pb2.EncoderConfigRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRtspEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetRtspEnabled',
            camera__pb2.RtspEnabledRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAiOverlay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/UpdateAiOverlay',
            camera__pb2.AiOverlayConfig.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOsdConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/UpdateOsdConfig',
            camera__pb2.OsdConfigRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOsdConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetOsdConfig',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.OsdConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconfigureEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/ReconfigureEncoder',
            camera__pb2.EncoderReconfigRequest.SerializeToString,
            camera__pb2.EncoderReconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetProfile',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.GetProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/ListProfiles',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.ListProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SwitchProfile',
            camera__pb2.SwitchProfileRequest.SerializeToString,
            camera__pb2.EncoderReconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/BackupProfile',
            camera__pb2.BackupProfileRequest.SerializeToString,
            camera__pb2.BackupProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconfigurePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/ReconfigurePipeline',
            camera__pb2.ReconfigurePipelineRequest.SerializeToString,
            camera__pb2.ReconfigurePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetSensorInfo',
            camera__pb2.GetSensorInfoRequest.SerializeToString,
            camera__pb2.SensorInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetStreamStatus',
            camera__pb2.GetStreamStatusRequest.SerializeToString,
            camera__pb2.GetStreamStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/AddStream',
            camera__pb2.AddStreamRequest.SerializeToString,
            camera__pb2.StreamOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/RemoveStream',
            camera__pb2.RemoveStreamRequest.SerializeToString,
            camera__pb2.StreamOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIrCut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetIrCut',
            camera__pb2.SetIrCutRequest.SerializeToString,
            camera__pb2.SetIrCutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIrCut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetIrCut',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.SetIrCutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLedDuty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetLedDuty',
            camera__pb2.SetLedDutyRequest.SerializeToString,
            camera__pb2.LedStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLedDuty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetLedDuty',
            camera__pb2.GetLedDutyRequest.SerializeToString,
            camera__pb2.LedStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceHardwareStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetDeviceHardwareStatus',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.DeviceHardwareStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def McuRawRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/McuRawRequest',
            camera__pb2.McuRawRequestMessage.SerializeToString,
            camera__pb2.McuRawResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetFan',
            camera__pb2.EnvCtrlRequest.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetFan',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetHeat',
            camera__pb2.EnvCtrlRequest.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetHeat',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRadar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetRadar',
            camera__pb2.EnvCtrlRequest.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRadar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetRadar',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAlarmOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetAlarmOut',
            camera__pb2.AlarmOutRequest.SerializeToString,
            camera__pb2.AlarmOutStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlarmOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetAlarmOut',
            camera__pb2.AlarmOutRequest.SerializeToString,
            camera__pb2.AlarmOutStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWiegandOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetWiegandOut',
            camera__pb2.WiegandOutRequest.SerializeToString,
            camera__pb2.AlarmOutStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWiegandOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetWiegandOut',
            camera__pb2.WiegandOutRequest.SerializeToString,
            camera__pb2.AlarmOutStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlarmOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetAlarmOutputs',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.AlarmOutputsState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/Rs485Init',
            camera__pb2.Rs485InitRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Deinit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/Rs485Deinit',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Tx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/Rs485Tx',
            camera__pb2.Rs485TxRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetCapabilities',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAudioCaptureDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/ListAudioCaptureDevices',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.ListAudioDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAudioPlaybackDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/ListAudioPlaybackDevices',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.ListAudioDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAudioCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StartAudioCapture',
            camera__pb2.AudioConfigRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudioCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StopAudioCapture',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAudioStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetAudioStatus',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.AudioStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAudioConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetAudioConfig',
            camera__pb2.AudioConfigRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAudioPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StartAudioPlayback',
            camera__pb2.AudioConfigRequest.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAudioPcm(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/aipc.camera.CameraControl/StreamAudioPcm',
            camera__pb2.AudioPcmChunk.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAudioPlayback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/StopAudioPlayback',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrivacyMaskConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/GetPrivacyMaskConfig',
            camera__pb2.Empty.SerializeToString,
            camera__pb2.PrivacyMaskConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPrivacyMaskConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.camera.CameraControl/SetPrivacyMaskConfig',
            camera__pb2.PrivacyMaskConfig.SerializeToString,
            camera__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
