# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import device_pb2 as device__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceControlStub(object):
    """============ Device Control Service ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetWhiteLight = channel.unary_unary(
                '/aipc.device.DeviceControl/SetWhiteLight',
                request_serializer=device__pb2.LightLevelRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetIrLed = channel.unary_unary(
                '/aipc.device.DeviceControl/SetIrLed',
                request_serializer=device__pb2.LightLevelRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetIrCut = channel.unary_unary(
                '/aipc.device.DeviceControl/SetIrCut',
                request_serializer=device__pb2.IrCutRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Pan = channel.unary_unary(
                '/aipc.device.DeviceControl/Pan',
                request_serializer=device__pb2.PanRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Tilt = channel.unary_unary(
                '/aipc.device.DeviceControl/Tilt',
                request_serializer=device__pb2.TiltRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.PTZStop = channel.unary_unary(
                '/aipc.device.DeviceControl/PTZStop',
                request_serializer=device__pb2.PTZStopRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SavePreset = channel.unary_unary(
                '/aipc.device.DeviceControl/SavePreset',
                request_serializer=device__pb2.PresetRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.CallPreset = channel.unary_unary(
                '/aipc.device.DeviceControl/CallPreset',
                request_serializer=device__pb2.PresetRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Zoom = channel.unary_unary(
                '/aipc.device.DeviceControl/Zoom',
                request_serializer=device__pb2.ZoomRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Focus = channel.unary_unary(
                '/aipc.device.DeviceControl/Focus',
                request_serializer=device__pb2.FocusRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetAutofocus = channel.unary_unary(
                '/aipc.device.DeviceControl/SetAutofocus',
                request_serializer=device__pb2.AutofocusRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetZoomLevel = channel.unary_unary(
                '/aipc.device.DeviceControl/SetZoomLevel',
                request_serializer=device__pb2.ZoomLevelRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.GetLensStatus = channel.unary_unary(
                '/aipc.device.DeviceControl/GetLensStatus',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.LensStatusResponse.FromString,
                _registered_method=True)
        self.SetFocusLevel = channel.unary_unary(
                '/aipc.device.DeviceControl/SetFocusLevel',
                request_serializer=device__pb2.FocusLevelRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.LensResetZero = channel.unary_unary(
                '/aipc.device.DeviceControl/LensResetZero',
                request_serializer=device__pb2.LensResetRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.ControlIris = channel.unary_unary(
                '/aipc.device.DeviceControl/ControlIris',
                request_serializer=device__pb2.IrisRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetIrisTarget = channel.unary_unary(
                '/aipc.device.DeviceControl/SetIrisTarget',
                request_serializer=device__pb2.IrisTargetRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetLensLimits = channel.unary_unary(
                '/aipc.device.DeviceControl/SetLensLimits',
                request_serializer=device__pb2.LensLimitsRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.StartOneShotAf = channel.unary_unary(
                '/aipc.device.DeviceControl/StartOneShotAf',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.AfJobResponse.FromString,
                _registered_method=True)
        self.StartZoomFollow = channel.unary_unary(
                '/aipc.device.DeviceControl/StartZoomFollow',
                request_serializer=device__pb2.ZoomFollowRequest.SerializeToString,
                response_deserializer=device__pb2.AfJobResponse.FromString,
                _registered_method=True)
        self.GetAutofocusStatus = channel.unary_unary(
                '/aipc.device.DeviceControl/GetAutofocusStatus',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.AfStatusResponse.FromString,
                _registered_method=True)
        self.CancelAutofocus = channel.unary_unary(
                '/aipc.device.DeviceControl/CancelAutofocus',
                request_serializer=device__pb2.AfJobRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.LensInit = channel.unary_unary(
                '/aipc.device.DeviceControl/LensInit',
                request_serializer=device__pb2.LensInitRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.LensGotoRatioDistance = channel.unary_unary(
                '/aipc.device.DeviceControl/LensGotoRatioDistance',
                request_serializer=device__pb2.GotoRatioDistanceRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.SetAfWindows = channel.unary_unary(
                '/aipc.device.DeviceControl/SetAfWindows',
                request_serializer=device__pb2.SetAfWindowsRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.GetAfMeasurement = channel.unary_unary(
                '/aipc.device.DeviceControl/GetAfMeasurement',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.AfMeasurementResponse.FromString,
                _registered_method=True)
        self.GPIOWrite = channel.unary_unary(
                '/aipc.device.DeviceControl/GPIOWrite',
                request_serializer=device__pb2.GPIOWriteRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.GPIORead = channel.unary_unary(
                '/aipc.device.DeviceControl/GPIORead',
                request_serializer=device__pb2.GPIOReadRequest.SerializeToString,
                response_deserializer=device__pb2.GPIOReadResponse.FromString,
                _registered_method=True)
        self.GPIOBatchRead = channel.unary_unary(
                '/aipc.device.DeviceControl/GPIOBatchRead',
                request_serializer=device__pb2.GPIOBatchReadRequest.SerializeToString,
                response_deserializer=device__pb2.GPIOBatchReadResponse.FromString,
                _registered_method=True)
        self.GetDeviceStatus = channel.unary_unary(
                '/aipc.device.DeviceControl/GetDeviceStatus',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.DeviceStatus.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/aipc.device.DeviceControl/SubscribeEvents',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.DeviceEvent.FromString,
                _registered_method=True)
        self.SetFan = channel.unary_unary(
                '/aipc.device.DeviceControl/SetFan',
                request_serializer=device__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetFan = channel.unary_unary(
                '/aipc.device.DeviceControl/GetFan',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetHeat = channel.unary_unary(
                '/aipc.device.DeviceControl/SetHeat',
                request_serializer=device__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetHeat = channel.unary_unary(
                '/aipc.device.DeviceControl/GetHeat',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetRadar = channel.unary_unary(
                '/aipc.device.DeviceControl/SetRadar',
                request_serializer=device__pb2.EnvCtrlRequest.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.GetRadar = channel.unary_unary(
                '/aipc.device.DeviceControl/GetRadar',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.EnvCtrlStatus.FromString,
                _registered_method=True)
        self.SetAlarmOut = channel.unary_unary(
                '/aipc.device.DeviceControl/SetAlarmOut',
                request_serializer=device__pb2.AlarmChannelRequest.SerializeToString,
                response_deserializer=device__pb2.AlarmChannelStatus.FromString,
                _registered_method=True)
        self.GetAlarmOut = channel.unary_unary(
                '/aipc.device.DeviceControl/GetAlarmOut',
                request_serializer=device__pb2.AlarmChannelRequest.SerializeToString,
                response_deserializer=device__pb2.AlarmChannelStatus.FromString,
                _registered_method=True)
        self.SetWiegandOut = channel.unary_unary(
                '/aipc.device.DeviceControl/SetWiegandOut',
                request_serializer=device__pb2.AlarmChannelRequest.SerializeToString,
                response_deserializer=device__pb2.AlarmChannelStatus.FromString,
                _registered_method=True)
        self.GetWiegandOut = channel.unary_unary(
                '/aipc.device.DeviceControl/GetWiegandOut',
                request_serializer=device__pb2.AlarmChannelRequest.SerializeToString,
                response_deserializer=device__pb2.AlarmChannelStatus.FromString,
                _registered_method=True)
        self.GetAlarmOutputs = channel.unary_unary(
                '/aipc.device.DeviceControl/GetAlarmOutputs',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.AlarmOutputsState.FromString,
                _registered_method=True)
        self.Rs485Init = channel.unary_unary(
                '/aipc.device.DeviceControl/Rs485Init',
                request_serializer=device__pb2.Rs485InitRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Rs485Deinit = channel.unary_unary(
                '/aipc.device.DeviceControl/Rs485Deinit',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.Rs485Tx = channel.unary_unary(
                '/aipc.device.DeviceControl/Rs485Tx',
                request_serializer=device__pb2.Rs485TxRequest.SerializeToString,
                response_deserializer=device__pb2.Status.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/aipc.device.DeviceControl/GetCapabilities',
                request_serializer=device__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)


class DeviceControlServicer(object):
    """============ Device Control Service ============

    """

    def SetWhiteLight(self, request, context):
        """Light control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIrLed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIrCut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pan(self, request, context):
        """PTZ control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tilt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PTZStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SavePreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Zoom(self, request, context):
        """Lens control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Focus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAutofocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetZoomLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLensStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFocusLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LensResetZero(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlIris(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIrisTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLensLimits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartOneShotAf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartZoomFollow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAutofocusStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAutofocus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LensInit(self, request, context):
        """AF0832 high-level API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LensGotoRatioDistance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAfWindows(self, request, context):
        """AF window / measurement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAfMeasurement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GPIOWrite(self, request, context):
        """GPIO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GPIORead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GPIOBatchRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceStatus(self, request, context):
        """Status query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFan(self, request, context):
        """Environment control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRadar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRadar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAlarmOut(self, request, context):
        """Alarm I/O
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlarmOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWiegandOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWiegandOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlarmOutputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Init(self, request, context):
        """RS485
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Deinit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rs485Tx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Capabilities (auto-detected from HAL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetWhiteLight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWhiteLight,
                    request_deserializer=device__pb2.LightLevelRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetIrLed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIrLed,
                    request_deserializer=device__pb2.LightLevelRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetIrCut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIrCut,
                    request_deserializer=device__pb2.IrCutRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Pan': grpc.unary_unary_rpc_method_handler(
                    servicer.Pan,
                    request_deserializer=device__pb2.PanRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Tilt': grpc.unary_unary_rpc_method_handler(
                    servicer.Tilt,
                    request_deserializer=device__pb2.TiltRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'PTZStop': grpc.unary_unary_rpc_method_handler(
                    servicer.PTZStop,
                    request_deserializer=device__pb2.PTZStopRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SavePreset': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePreset,
                    request_deserializer=device__pb2.PresetRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'CallPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.CallPreset,
                    request_deserializer=device__pb2.PresetRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Zoom': grpc.unary_unary_rpc_method_handler(
                    servicer.Zoom,
                    request_deserializer=device__pb2.ZoomRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Focus': grpc.unary_unary_rpc_method_handler(
                    servicer.Focus,
                    request_deserializer=device__pb2.FocusRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetAutofocus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAutofocus,
                    request_deserializer=device__pb2.AutofocusRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetZoomLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZoomLevel,
                    request_deserializer=device__pb2.ZoomLevelRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'GetLensStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLensStatus,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.LensStatusResponse.SerializeToString,
            ),
            'SetFocusLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFocusLevel,
                    request_deserializer=device__pb2.FocusLevelRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'LensResetZero': grpc.unary_unary_rpc_method_handler(
                    servicer.LensResetZero,
                    request_deserializer=device__pb2.LensResetRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'ControlIris': grpc.unary_unary_rpc_method_handler(
                    servicer.ControlIris,
                    request_deserializer=device__pb2.IrisRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetIrisTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIrisTarget,
                    request_deserializer=device__pb2.IrisTargetRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetLensLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLensLimits,
                    request_deserializer=device__pb2.LensLimitsRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'StartOneShotAf': grpc.unary_unary_rpc_method_handler(
                    servicer.StartOneShotAf,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.AfJobResponse.SerializeToString,
            ),
            'StartZoomFollow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartZoomFollow,
                    request_deserializer=device__pb2.ZoomFollowRequest.FromString,
                    response_serializer=device__pb2.AfJobResponse.SerializeToString,
            ),
            'GetAutofocusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAutofocusStatus,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.AfStatusResponse.SerializeToString,
            ),
            'CancelAutofocus': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAutofocus,
                    request_deserializer=device__pb2.AfJobRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'LensInit': grpc.unary_unary_rpc_method_handler(
                    servicer.LensInit,
                    request_deserializer=device__pb2.LensInitRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'LensGotoRatioDistance': grpc.unary_unary_rpc_method_handler(
                    servicer.LensGotoRatioDistance,
                    request_deserializer=device__pb2.GotoRatioDistanceRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'SetAfWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAfWindows,
                    request_deserializer=device__pb2.SetAfWindowsRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'GetAfMeasurement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAfMeasurement,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.AfMeasurementResponse.SerializeToString,
            ),
            'GPIOWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.GPIOWrite,
                    request_deserializer=device__pb2.GPIOWriteRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'GPIORead': grpc.unary_unary_rpc_method_handler(
                    servicer.GPIORead,
                    request_deserializer=device__pb2.GPIOReadRequest.FromString,
                    response_serializer=device__pb2.GPIOReadResponse.SerializeToString,
            ),
            'GPIOBatchRead': grpc.unary_unary_rpc_method_handler(
                    servicer.GPIOBatchRead,
                    request_deserializer=device__pb2.GPIOBatchReadRequest.FromString,
                    response_serializer=device__pb2.GPIOBatchReadResponse.SerializeToString,
            ),
            'GetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceStatus,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.DeviceStatus.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.DeviceEvent.SerializeToString,
            ),
            'SetFan': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFan,
                    request_deserializer=device__pb2.EnvCtrlRequest.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetFan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFan,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetHeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeat,
                    request_deserializer=device__pb2.EnvCtrlRequest.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetHeat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeat,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetRadar': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRadar,
                    request_deserializer=device__pb2.EnvCtrlRequest.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'GetRadar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRadar,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.EnvCtrlStatus.SerializeToString,
            ),
            'SetAlarmOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAlarmOut,
                    request_deserializer=device__pb2.AlarmChannelRequest.FromString,
                    response_serializer=device__pb2.AlarmChannelStatus.SerializeToString,
            ),
            'GetAlarmOut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarmOut,
                    request_deserializer=device__pb2.AlarmChannelRequest.FromString,
                    response_serializer=device__pb2.AlarmChannelStatus.SerializeToString,
            ),
            'SetWiegandOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWiegandOut,
                    request_deserializer=device__pb2.AlarmChannelRequest.FromString,
                    response_serializer=device__pb2.AlarmChannelStatus.SerializeToString,
            ),
            'GetWiegandOut': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWiegandOut,
                    request_deserializer=device__pb2.AlarmChannelRequest.FromString,
                    response_serializer=device__pb2.AlarmChannelStatus.SerializeToString,
            ),
            'GetAlarmOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlarmOutputs,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.AlarmOutputsState.SerializeToString,
            ),
            'Rs485Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Init,
                    request_deserializer=device__pb2.Rs485InitRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Rs485Deinit': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Deinit,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'Rs485Tx': grpc.unary_unary_rpc_method_handler(
                    servicer.Rs485Tx,
                    request_deserializer=device__pb2.Rs485TxRequest.FromString,
                    response_serializer=device__pb2.Status.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=device__pb2.Empty.FromString,
                    response_serializer=device__pb2.CapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipc.device.DeviceControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipc.device.DeviceControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceControl(object):
    """============ Device Control Service ============

    """

    @staticmethod
    def SetWhiteLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetWhiteLight',
            device__pb2.LightLevelRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIrLed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetIrLed',
            device__pb2.LightLevelRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIrCut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetIrCut',
            device__pb2.IrCutRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Pan',
            device__pb2.PanRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tilt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Tilt',
            device__pb2.TiltRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PTZStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/PTZStop',
            device__pb2.PTZStopRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SavePreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SavePreset',
            device__pb2.PresetRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/CallPreset',
            device__pb2.PresetRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Zoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Zoom',
            device__pb2.ZoomRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Focus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Focus',
            device__pb2.FocusRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAutofocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetAutofocus',
            device__pb2.AutofocusRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetZoomLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetZoomLevel',
            device__pb2.ZoomLevelRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLensStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetLensStatus',
            device__pb2.Empty.SerializeToString,
            device__pb2.LensStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFocusLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetFocusLevel',
            device__pb2.FocusLevelRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LensResetZero(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/LensResetZero',
            device__pb2.LensResetRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlIris(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/ControlIris',
            device__pb2.IrisRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetIrisTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetIrisTarget',
            device__pb2.IrisTargetRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLensLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetLensLimits',
            device__pb2.LensLimitsRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartOneShotAf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/StartOneShotAf',
            device__pb2.Empty.SerializeToString,
            device__pb2.AfJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartZoomFollow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/StartZoomFollow',
            device__pb2.ZoomFollowRequest.SerializeToString,
            device__pb2.AfJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAutofocusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetAutofocusStatus',
            device__pb2.Empty.SerializeToString,
            device__pb2.AfStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAutofocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/CancelAutofocus',
            device__pb2.AfJobRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LensInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/LensInit',
            device__pb2.LensInitRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LensGotoRatioDistance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/LensGotoRatioDistance',
            device__pb2.GotoRatioDistanceRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAfWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetAfWindows',
            device__pb2.SetAfWindowsRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAfMeasurement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetAfMeasurement',
            device__pb2.Empty.SerializeToString,
            device__pb2.AfMeasurementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GPIOWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GPIOWrite',
            device__pb2.GPIOWriteRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GPIORead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GPIORead',
            device__pb2.GPIOReadRequest.SerializeToString,
            device__pb2.GPIOReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GPIOBatchRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GPIOBatchRead',
            device__pb2.GPIOBatchReadRequest.SerializeToString,
            device__pb2.GPIOBatchReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetDeviceStatus',
            device__pb2.Empty.SerializeToString,
            device__pb2.DeviceStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipc.device.DeviceControl/SubscribeEvents',
            device__pb2.Empty.SerializeToString,
            device__pb2.DeviceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetFan',
            device__pb2.EnvCtrlRequest.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetFan',
            device__pb2.Empty.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetHeat',
            device__pb2.EnvCtrlRequest.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetHeat',
            device__pb2.Empty.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRadar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetRadar',
            device__pb2.EnvCtrlRequest.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRadar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetRadar',
            device__pb2.Empty.SerializeToString,
            device__pb2.EnvCtrlStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAlarmOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetAlarmOut',
            device__pb2.AlarmChannelRequest.SerializeToString,
            device__pb2.AlarmChannelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlarmOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetAlarmOut',
            device__pb2.AlarmChannelRequest.SerializeToString,
            device__pb2.AlarmChannelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWiegandOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/SetWiegandOut',
            device__pb2.AlarmChannelRequest.SerializeToString,
            device__pb2.AlarmChannelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWiegandOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetWiegandOut',
            device__pb2.AlarmChannelRequest.SerializeToString,
            device__pb2.AlarmChannelStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlarmOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetAlarmOutputs',
            device__pb2.Empty.SerializeToString,
            device__pb2.AlarmOutputsState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Rs485Init',
            device__pb2.Rs485InitRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Deinit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Rs485Deinit',
            device__pb2.Empty.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rs485Tx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/Rs485Tx',
            device__pb2.Rs485TxRequest.SerializeToString,
            device__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.device.DeviceControl/GetCapabilities',
            device__pb2.Empty.SerializeToString,
            device__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
