# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import event_pb2 as event__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in event_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventBusStub(object):
    """============ Event Bus Service ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/aipc.event.EventBus/Publish',
                request_serializer=event__pb2.PublishRequest.SerializeToString,
                response_deserializer=event__pb2.PublishResponse.FromString,
                _registered_method=True)
        self.PublishBatch = channel.stream_unary(
                '/aipc.event.EventBus/PublishBatch',
                request_serializer=event__pb2.PublishRequest.SerializeToString,
                response_deserializer=event__pb2.Status.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/aipc.event.EventBus/Subscribe',
                request_serializer=event__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=event__pb2.Event.FromString,
                _registered_method=True)
        self.Unsubscribe = channel.unary_unary(
                '/aipc.event.EventBus/Unsubscribe',
                request_serializer=event__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=event__pb2.Status.FromString,
                _registered_method=True)
        self.ListTopics = channel.unary_unary(
                '/aipc.event.EventBus/ListTopics',
                request_serializer=event__pb2.Empty.SerializeToString,
                response_deserializer=event__pb2.TopicListResponse.FromString,
                _registered_method=True)
        self.GetTopicInfo = channel.unary_unary(
                '/aipc.event.EventBus/GetTopicInfo',
                request_serializer=event__pb2.TopicInfo.SerializeToString,
                response_deserializer=event__pb2.TopicInfo.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/aipc.event.EventBus/GetStats',
                request_serializer=event__pb2.Empty.SerializeToString,
                response_deserializer=event__pb2.SystemStats.FromString,
                _registered_method=True)
        self.GetTopicStats = channel.unary_unary(
                '/aipc.event.EventBus/GetTopicStats',
                request_serializer=event__pb2.TopicInfo.SerializeToString,
                response_deserializer=event__pb2.EventStats.FromString,
                _registered_method=True)


class EventBusServicer(object):
    """============ Event Bus Service ============

    """

    def Publish(self, request, context):
        """Publish event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishBatch(self, request_iterator, context):
        """Batch publish
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Subscribe to events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unsubscribe(self, request, context):
        """Unsubscribe
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTopics(self, request, context):
        """Topic management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopicInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopicStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=event__pb2.PublishRequest.FromString,
                    response_serializer=event__pb2.PublishResponse.SerializeToString,
            ),
            'PublishBatch': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishBatch,
                    request_deserializer=event__pb2.PublishRequest.FromString,
                    response_serializer=event__pb2.Status.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=event__pb2.SubscribeRequest.FromString,
                    response_serializer=event__pb2.Event.SerializeToString,
            ),
            'Unsubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Unsubscribe,
                    request_deserializer=event__pb2.SubscribeRequest.FromString,
                    response_serializer=event__pb2.Status.SerializeToString,
            ),
            'ListTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTopics,
                    request_deserializer=event__pb2.Empty.FromString,
                    response_serializer=event__pb2.TopicListResponse.SerializeToString,
            ),
            'GetTopicInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopicInfo,
                    request_deserializer=event__pb2.TopicInfo.FromString,
                    response_serializer=event__pb2.TopicInfo.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=event__pb2.Empty.FromString,
                    response_serializer=event__pb2.SystemStats.SerializeToString,
            ),
            'GetTopicStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopicStats,
                    request_deserializer=event__pb2.TopicInfo.FromString,
                    response_serializer=event__pb2.EventStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipc.event.EventBus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipc.event.EventBus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBus(object):
    """============ Event Bus Service ============

    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/Publish',
            event__pb2.PublishRequest.SerializeToString,
            event__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishBatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/aipc.event.EventBus/PublishBatch',
            event__pb2.PublishRequest.SerializeToString,
            event__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipc.event.EventBus/Subscribe',
            event__pb2.SubscribeRequest.SerializeToString,
            event__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unsubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/Unsubscribe',
            event__pb2.SubscribeRequest.SerializeToString,
            event__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/ListTopics',
            event__pb2.Empty.SerializeToString,
            event__pb2.TopicListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopicInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/GetTopicInfo',
            event__pb2.TopicInfo.SerializeToString,
            event__pb2.TopicInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/GetStats',
            event__pb2.Empty.SerializeToString,
            event__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopicStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.event.EventBus/GetTopicStats',
            event__pb2.TopicInfo.SerializeToString,
            event__pb2.EventStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
