# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """============ Inference Service ============

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/aipc.inference.InferenceService/RegisterModel',
                request_serializer=inference__pb2.ModelRegisterRequest.SerializeToString,
                response_deserializer=inference__pb2.ModelRegisterResponse.FromString,
                _registered_method=True)
        self.UnregisterModel = channel.unary_unary(
                '/aipc.inference.InferenceService/UnregisterModel',
                request_serializer=inference__pb2.ModelInfo.SerializeToString,
                response_deserializer=inference__pb2.Status.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/aipc.inference.InferenceService/ListModels',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.ModelListResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/aipc.inference.InferenceService/GetModelInfo',
                request_serializer=inference__pb2.ModelInfo.SerializeToString,
                response_deserializer=inference__pb2.ModelInfo.FromString,
                _registered_method=True)
        self.Infer = channel.unary_unary(
                '/aipc.inference.InferenceService/Infer',
                request_serializer=inference__pb2.InferRequest.SerializeToString,
                response_deserializer=inference__pb2.InferResponse.FromString,
                _registered_method=True)
        self.InferBatch = channel.unary_unary(
                '/aipc.inference.InferenceService/InferBatch',
                request_serializer=inference__pb2.InferBatchRequest.SerializeToString,
                response_deserializer=inference__pb2.InferBatchResponse.FromString,
                _registered_method=True)
        self.StreamInfer = channel.unary_stream(
                '/aipc.inference.InferenceService/StreamInfer',
                request_serializer=inference__pb2.StreamInferRequest.SerializeToString,
                response_deserializer=inference__pb2.StreamInferResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/aipc.inference.InferenceService/CreateSession',
                request_serializer=inference__pb2.SessionConfig.SerializeToString,
                response_deserializer=inference__pb2.SessionCreateResponse.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/aipc.inference.InferenceService/DestroySession',
                request_serializer=inference__pb2.SessionConfig.SerializeToString,
                response_deserializer=inference__pb2.Status.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/aipc.inference.InferenceService/GetStats',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.SystemStats.FromString,
                _registered_method=True)
        self.UpdatePostprocessConfig = channel.unary_unary(
                '/aipc.inference.InferenceService/UpdatePostprocessConfig',
                request_serializer=inference__pb2.UpdatePostprocessConfigRequest.SerializeToString,
                response_deserializer=inference__pb2.UpdatePostprocessConfigResponse.FromString,
                _registered_method=True)
        self.EncodeText = channel.unary_unary(
                '/aipc.inference.InferenceService/EncodeText',
                request_serializer=inference__pb2.EncodeTextRequest.SerializeToString,
                response_deserializer=inference__pb2.EncodeTextResponse.FromString,
                _registered_method=True)
        self.GenaiCreateSession = channel.unary_unary(
                '/aipc.inference.InferenceService/GenaiCreateSession',
                request_serializer=inference__pb2.GenaiCreateSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.GenaiCreateSessionResponse.FromString,
                _registered_method=True)
        self.GenaiDestroySession = channel.unary_unary(
                '/aipc.inference.InferenceService/GenaiDestroySession',
                request_serializer=inference__pb2.GenaiCreateSessionRequest.SerializeToString,
                response_deserializer=inference__pb2.Status.FromString,
                _registered_method=True)
        self.GenaiGenerate = channel.unary_stream(
                '/aipc.inference.InferenceService/GenaiGenerate',
                request_serializer=inference__pb2.GenaiGenerateRequest.SerializeToString,
                response_deserializer=inference__pb2.GenaiGenerateResponse.FromString,
                _registered_method=True)
        self.GenaiAbort = channel.unary_unary(
                '/aipc.inference.InferenceService/GenaiAbort',
                request_serializer=inference__pb2.GenaiAbortRequest.SerializeToString,
                response_deserializer=inference__pb2.Status.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """============ Inference Service ============

    """

    def RegisterModel(self, request, context):
        """Model management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Infer(self, request, context):
        """Single inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferBatch(self, request, context):
        """Batch inference — submit multiple model inferences in one RPC.
        ai-runtime runs them in parallel and returns all results together.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInfer(self, request, context):
        """Stream inference
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePostprocessConfig(self, request, context):
        """Dynamic postprocess configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeText(self, request, context):
        """CLIP text encoding — encode a text string to a CLIP embedding via NPU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenaiCreateSession(self, request, context):
        """GenAI (LLM/VLM) streaming generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenaiDestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenaiGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenaiAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=inference__pb2.ModelRegisterRequest.FromString,
                    response_serializer=inference__pb2.ModelRegisterResponse.SerializeToString,
            ),
            'UnregisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterModel,
                    request_deserializer=inference__pb2.ModelInfo.FromString,
                    response_serializer=inference__pb2.Status.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.ModelListResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=inference__pb2.ModelInfo.FromString,
                    response_serializer=inference__pb2.ModelInfo.SerializeToString,
            ),
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=inference__pb2.InferRequest.FromString,
                    response_serializer=inference__pb2.InferResponse.SerializeToString,
            ),
            'InferBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.InferBatch,
                    request_deserializer=inference__pb2.InferBatchRequest.FromString,
                    response_serializer=inference__pb2.InferBatchResponse.SerializeToString,
            ),
            'StreamInfer': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=inference__pb2.StreamInferRequest.FromString,
                    response_serializer=inference__pb2.StreamInferResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=inference__pb2.SessionConfig.FromString,
                    response_serializer=inference__pb2.SessionCreateResponse.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=inference__pb2.SessionConfig.FromString,
                    response_serializer=inference__pb2.Status.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.SystemStats.SerializeToString,
            ),
            'UpdatePostprocessConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePostprocessConfig,
                    request_deserializer=inference__pb2.UpdatePostprocessConfigRequest.FromString,
                    response_serializer=inference__pb2.UpdatePostprocessConfigResponse.SerializeToString,
            ),
            'EncodeText': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeText,
                    request_deserializer=inference__pb2.EncodeTextRequest.FromString,
                    response_serializer=inference__pb2.EncodeTextResponse.SerializeToString,
            ),
            'GenaiCreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GenaiCreateSession,
                    request_deserializer=inference__pb2.GenaiCreateSessionRequest.FromString,
                    response_serializer=inference__pb2.GenaiCreateSessionResponse.SerializeToString,
            ),
            'GenaiDestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.GenaiDestroySession,
                    request_deserializer=inference__pb2.GenaiCreateSessionRequest.FromString,
                    response_serializer=inference__pb2.Status.SerializeToString,
            ),
            'GenaiGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.GenaiGenerate,
                    request_deserializer=inference__pb2.GenaiGenerateRequest.FromString,
                    response_serializer=inference__pb2.GenaiGenerateResponse.SerializeToString,
            ),
            'GenaiAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.GenaiAbort,
                    request_deserializer=inference__pb2.GenaiAbortRequest.FromString,
                    response_serializer=inference__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aipc.inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aipc.inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """============ Inference Service ============

    """

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/RegisterModel',
            inference__pb2.ModelRegisterRequest.SerializeToString,
            inference__pb2.ModelRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/UnregisterModel',
            inference__pb2.ModelInfo.SerializeToString,
            inference__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/ListModels',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.ModelListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/GetModelInfo',
            inference__pb2.ModelInfo.SerializeToString,
            inference__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/Infer',
            inference__pb2.InferRequest.SerializeToString,
            inference__pb2.InferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InferBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/InferBatch',
            inference__pb2.InferBatchRequest.SerializeToString,
            inference__pb2.InferBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipc.inference.InferenceService/StreamInfer',
            inference__pb2.StreamInferRequest.SerializeToString,
            inference__pb2.StreamInferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/CreateSession',
            inference__pb2.SessionConfig.SerializeToString,
            inference__pb2.SessionCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/DestroySession',
            inference__pb2.SessionConfig.SerializeToString,
            inference__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/GetStats',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.SystemStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePostprocessConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/UpdatePostprocessConfig',
            inference__pb2.UpdatePostprocessConfigRequest.SerializeToString,
            inference__pb2.UpdatePostprocessConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/EncodeText',
            inference__pb2.EncodeTextRequest.SerializeToString,
            inference__pb2.EncodeTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenaiCreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/GenaiCreateSession',
            inference__pb2.GenaiCreateSessionRequest.SerializeToString,
            inference__pb2.GenaiCreateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenaiDestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/GenaiDestroySession',
            inference__pb2.GenaiCreateSessionRequest.SerializeToString,
            inference__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenaiGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aipc.inference.InferenceService/GenaiGenerate',
            inference__pb2.GenaiGenerateRequest.SerializeToString,
            inference__pb2.GenaiGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenaiAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aipc.inference.InferenceService/GenaiAbort',
            inference__pb2.GenaiAbortRequest.SerializeToString,
            inference__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
